-----------------------------------------
-- Crea el esquema de la base de datos --
-----------------------------------------

CREATE OR REPLACE TABLE APP_COMPONENTE
(
	ID BIGINT(19) AUTO_INCREMENT
		PRIMARY KEY,
	NOMBRE VARCHAR(30) NULL
);

CREATE OR REPLACE TABLE AUTOR
(
	ID BIGINT(19) AUTO_INCREMENT
		PRIMARY KEY,
	NOMBRE VARCHAR(25) NOT NULL,
	APELLIDO1 VARCHAR(25) NULL,
	APELLIDO2 VARCHAR(25) NULL,
	BIOGRAFIA VARCHAR(500) NULL,
	LINK_FOTO VARCHAR(500) NULL
);

CREATE OR REPLACE TABLE COLECCION
(
	ID BIGINT(19) AUTO_INCREMENT
		PRIMARY KEY,
	NOMBRE VARCHAR(50) NOT NULL,
	DESCRIPCION VARCHAR(500) NULL
);

CREATE OR REPLACE TABLE EDITORIAL
(
	ID BIGINT(19) AUTO_INCREMENT
		PRIMARY KEY,
	NOMBRE VARCHAR(50) NOT NULL,
	DIRECCION VARCHAR(100) NULL,
	PROVINCIA VARCHAR(50) NULL,
	CCAA VARCHAR(25) NULL,
	TELEFONO1 BIGINT(9) NULL,
	TELEFONO2 BIGINT(9) NULL,
	ENLACE_WEB VARCHAR(100) NULL,
	DESCRIPCION VARCHAR(500) NULL
);

CREATE OR REPLACE TABLE ESTADO
(
	ID BIGINT(19) AUTO_INCREMENT
		PRIMARY KEY,
	ESTADO VARCHAR(25) NOT NULL,
	ID_COMPONENTE BIGINT(19) NOT NULL,
	CONSTRAINT ESTADO_IBFK_1
		FOREIGN KEY (ID_COMPONENTE) REFERENCES APP_COMPONENTE (ID)
);

CREATE OR REPLACE INDEX ID_COMPONENTE
	ON ESTADO (ID_COMPONENTE);

CREATE OR REPLACE TABLE LIBRO
(
	ID BIGINT(19) AUTO_INCREMENT
		PRIMARY KEY,
	ISBN VARCHAR(100) NULL,
	TITULO VARCHAR(100) NULL,
	SUBTITULO VARCHAR(500) NULL,
	SINOPSIS VARCHAR(5000) NULL,
	PAGINAS INT NULL,
	FORMATO VARCHAR(50) NULL,
	FECHA_PUBLICACION DATE NULL,
	FECHA_EDICION DATE NULL,
	FECHA_DISPONIBLE DATE NULL,
	VISIBLE TINYINT(1) NULL,
	IDIOMA VARCHAR(50) NULL,
	NOTAS VARCHAR(500) NULL,
	STOCK INT NULL,
	PRECIO FLOAT(6,2) NULL,
	NOMBRE_PORTADA VARCHAR(500) NULL,
	ID_EDITORIAL BIGINT(19) NULL,
	CONSTRAINT ISBN
		UNIQUE (ISBN),
	CONSTRAINT ISBN_2
		UNIQUE (ISBN),
	CONSTRAINT LIBRO_IBFK_1
		FOREIGN KEY (ID_EDITORIAL) REFERENCES EDITORIAL (ID)
			ON UPDATE CASCADE ON DELETE CASCADE
);

CREATE OR REPLACE INDEX ID_EDITORIAL
	ON LIBRO (ID_EDITORIAL);

CREATE OR REPLACE TABLE LIBRO_AUTOR
(
	ID_LIBRO BIGINT(19) NOT NULL,
	ID_AUTOR BIGINT(19) NOT NULL,
	PRIMARY KEY (ID_LIBRO, ID_AUTOR),
	CONSTRAINT LIBRO_AUTOR_IBFK_1
		FOREIGN KEY (ID_LIBRO) REFERENCES LIBRO (ID)
			ON UPDATE CASCADE ON DELETE CASCADE,
	CONSTRAINT LIBRO_AUTOR_IBFK_2
		FOREIGN KEY (ID_AUTOR) REFERENCES AUTOR (ID)
			ON UPDATE CASCADE ON DELETE CASCADE
);

CREATE OR REPLACE INDEX ID_AUTOR
	ON LIBRO_AUTOR (ID_AUTOR);

CREATE OR REPLACE TABLE LIBRO_COLECCION
(
	ID_LIBRO BIGINT(19) NOT NULL,
	ID_COLECCION BIGINT(19) NOT NULL,
	PRIMARY KEY (ID_LIBRO, ID_COLECCION),
	CONSTRAINT LIBRO_COLECCION_IBFK_1
		FOREIGN KEY (ID_LIBRO) REFERENCES LIBRO (ID)
			ON UPDATE CASCADE ON DELETE CASCADE,
	CONSTRAINT LIBRO_COLECCION_IBFK_2
		FOREIGN KEY (ID_COLECCION) REFERENCES COLECCION (ID)
			ON UPDATE CASCADE ON DELETE CASCADE
);

CREATE OR REPLACE INDEX ID_COLECCION
	ON LIBRO_COLECCION (ID_COLECCION);

CREATE OR REPLACE TABLE ROL
(
	ID BIGINT(19) AUTO_INCREMENT
		PRIMARY KEY,
	NOMBRE_ROL VARCHAR(25) NOT NULL
);

CREATE OR REPLACE TABLE TEMATICA
(
	ID BIGINT(19) AUTO_INCREMENT
		PRIMARY KEY,
	NOMBRE VARCHAR(50) NOT NULL,
	DESCRIPCION VARCHAR(500) NULL
);

CREATE OR REPLACE TABLE LIBRO_TEMATICA
(
	ID_LIBRO BIGINT(19) NOT NULL,
	ID_TEMATICA BIGINT(19) NOT NULL,
	PRIMARY KEY (ID_LIBRO, ID_TEMATICA),
	CONSTRAINT LIBRO_TEMATICA_IBFK_1
		FOREIGN KEY (ID_LIBRO) REFERENCES LIBRO (ID)
			ON UPDATE CASCADE ON DELETE CASCADE,
	CONSTRAINT LIBRO_TEMATICA_IBFK_2
		FOREIGN KEY (ID_TEMATICA) REFERENCES TEMATICA (ID)
			ON UPDATE CASCADE ON DELETE CASCADE
);

CREATE OR REPLACE INDEX ID_TEMATICA
	ON LIBRO_TEMATICA (ID_TEMATICA);

CREATE OR REPLACE TABLE TIPO_ENTREGA
(
	ID BIGINT(19) AUTO_INCREMENT
		PRIMARY KEY,
	TIPO_ENTREGA VARCHAR(25) NOT NULL
);

CREATE OR REPLACE TABLE TIPO_OPERACION
(
	ID BIGINT(19) AUTO_INCREMENT
		PRIMARY KEY,
	TIPO_OPERACION VARCHAR(25) NOT NULL
);

CREATE OR REPLACE TABLE TIPO_TARJETA
(
	ID BIGINT(19) AUTO_INCREMENT
		PRIMARY KEY,
	NOMBRE VARCHAR(25) NOT NULL
);

CREATE OR REPLACE TABLE USUARIO
(
	ID BIGINT(19) AUTO_INCREMENT
		PRIMARY KEY,
	USUARIO VARCHAR(25) NOT NULL,
	PASSWORD VARCHAR(255) NOT NULL,
	EMAIL VARCHAR(50) NOT NULL,
	DNI VARCHAR(9) NULL,
	NOMBRE VARCHAR(25) NULL,
	APELLIDO1 VARCHAR(25) NULL,
	APELLIDO2 VARCHAR(25) NULL,
	TELEFONO1 BIGINT(9) NULL,
	TELEFONO2 BIGINT(9) NULL,
	FECHA_NACIMIENTO DATE NULL,
	ACTIVO INT NULL,
	CONSTRAINT EMAIL
		UNIQUE (EMAIL),
	CONSTRAINT USUARIO
		UNIQUE (USUARIO)
);

CREATE OR REPLACE TABLE CESTA
(
	ID_USUARIO BIGINT(19) NOT NULL,
	ID_LIBRO BIGINT(19) NOT NULL,
	CANTIDAD INT NOT NULL,
	PRIMARY KEY (ID_USUARIO, ID_LIBRO),
	CONSTRAINT CESTA_IBFK_1
		FOREIGN KEY (ID_USUARIO) REFERENCES USUARIO (ID)
			ON UPDATE CASCADE ON DELETE CASCADE,
	CONSTRAINT CESTA_IBFK_2
		FOREIGN KEY (ID_LIBRO) REFERENCES LIBRO (ID)
			ON UPDATE CASCADE ON DELETE CASCADE
);

CREATE OR REPLACE INDEX ID_LIBRO
	ON CESTA (ID_LIBRO);

CREATE OR REPLACE TABLE COMENTARIO
(
	FECHA_COMENTARIO DATE NOT NULL,
	COMENTARIO VARCHAR(500) NULL,
	ESTRELLAS INT NULL,
	ID_ESTADO BIGINT(19) NULL,
	ANONIMO TINYINT(1) NULL,
	ID_LIBRO BIGINT(19) NOT NULL,
	ID_USUARIO BIGINT(19) NOT NULL,
	PRIMARY KEY (ID_LIBRO, ID_USUARIO),
	CONSTRAINT COMENTARIO_IBFK_1
		FOREIGN KEY (ID_ESTADO) REFERENCES ESTADO (ID)
			ON UPDATE CASCADE ON DELETE CASCADE,
	CONSTRAINT COMENTARIO_IBFK_2
		FOREIGN KEY (ID_USUARIO) REFERENCES USUARIO (ID)
			ON UPDATE CASCADE ON DELETE CASCADE,
	CONSTRAINT COMENTARIO_IBFK_3
		FOREIGN KEY (ID_LIBRO) REFERENCES LIBRO (ID)
			ON UPDATE CASCADE ON DELETE CASCADE
);

CREATE OR REPLACE INDEX ID_ESTADO
	ON COMENTARIO (ID_ESTADO);

CREATE OR REPLACE INDEX ID_USUARIO
	ON COMENTARIO (ID_USUARIO);

CREATE OR REPLACE TABLE CONSULTA
(
	ID BIGINT(19) AUTO_INCREMENT
		PRIMARY KEY,
	NOMBRE VARCHAR(25) NULL,
	APELLIDO1 VARCHAR(25) NULL,
	APELLIDO2 VARCHAR(25) NULL,
	EMAIL VARCHAR(50) NULL,
	TELEFONO BIGINT(9) NULL,
	FECHA_CONSULTA DATE NOT NULL,
	HORA_CONSULTA TIME NULL,
	FECHA_FIN DATE NULL,
	CONSULTA VARCHAR(1000) NOT NULL,
	ID_USUARIO BIGINT(19) NULL,
	ID_ESTADO BIGINT(19) NULL,
	ID_TIPO_OPERACION BIGINT(19) NOT NULL,
	CONSTRAINT CONSULTA_IBFK_1
		FOREIGN KEY (ID_USUARIO) REFERENCES USUARIO (ID)
			ON UPDATE CASCADE ON DELETE CASCADE,
	CONSTRAINT CONSULTA_IBFK_2
		FOREIGN KEY (ID_ESTADO) REFERENCES ESTADO (ID)
			ON UPDATE CASCADE ON DELETE CASCADE,
	CONSTRAINT CONSULTA_IBFK_3
		FOREIGN KEY (ID_TIPO_OPERACION) REFERENCES TIPO_OPERACION (ID)
			ON UPDATE CASCADE ON DELETE CASCADE
);

CREATE OR REPLACE INDEX ID_ESTADO
	ON CONSULTA (ID_ESTADO);

CREATE OR REPLACE INDEX ID_TIPO_OPERACION
	ON CONSULTA (ID_TIPO_OPERACION);

CREATE OR REPLACE INDEX ID_USUARIO
	ON CONSULTA (ID_USUARIO);

CREATE OR REPLACE TABLE DIRECCION
(
	ID BIGINT(19) AUTO_INCREMENT
		PRIMARY KEY,
	NOMBRE_PERSONALIZADO VARCHAR(50) NULL,
	NOMBRE_RECEPTOR VARCHAR(25) NOT NULL,
	APELLIDO1_RECEPTOR VARCHAR(25) NULL,
	APELLIDO2_RECEPTOR VARCHAR(25) NULL,
	DIRECCION VARCHAR(100) NOT NULL,
	CODIGO_POSTAL INT(5) NULL,
	POBLACION VARCHAR(50) NULL,
	PROVINCIA VARCHAR(25) NULL,
	PAIS VARCHAR(50) NULL,
	ID_USUARIO BIGINT(19) NULL,
	CONSTRAINT DIRECCION_IBFK_1
		FOREIGN KEY (ID_USUARIO) REFERENCES USUARIO (ID)
			ON UPDATE CASCADE ON DELETE CASCADE
);

CREATE OR REPLACE INDEX ID_USUARIO
	ON DIRECCION (ID_USUARIO);

CREATE OR REPLACE TABLE ENCARGO
(
	ID BIGINT(19) AUTO_INCREMENT
		PRIMARY KEY,
	ISBN VARCHAR(100) NULL,
	TITULO VARCHAR(100) NULL,
	CANTIDAD INT NULL,
	FECHA_ENCARGO DATE NULL,
	HORA_ENCARGO TIME NULL,
	FECHA_FIN DATE NULL,
	ID_ESTADO BIGINT(19) NULL,
	ID_TIPO_ENTREGA BIGINT(19) NULL,
	ID_LIBRO BIGINT(19) NULL,
	ID_USUARIO BIGINT(19) NULL,
	ID_TIPO_OPERACION BIGINT(19) NOT NULL,
	NOMBRE VARCHAR(25) NULL,
	APELLIDO1 VARCHAR(25) NULL,
	APELLIDO2 VARCHAR(25) NULL,
	EMAIL VARCHAR(50) NULL,
	TELEFONO BIGINT(9) NULL,
	NOTAS VARCHAR(250) NULL,
	CONSTRAINT ENCARGO_IBFK_1
		FOREIGN KEY (ID_ESTADO) REFERENCES ESTADO (ID)
			ON UPDATE CASCADE ON DELETE CASCADE,
	CONSTRAINT ENCARGO_IBFK_2
		FOREIGN KEY (ID_TIPO_ENTREGA) REFERENCES TIPO_ENTREGA (ID)
			ON UPDATE CASCADE ON DELETE CASCADE,
	CONSTRAINT ENCARGO_IBFK_3
		FOREIGN KEY (ID_LIBRO) REFERENCES LIBRO (ID)
			ON UPDATE CASCADE ON DELETE CASCADE,
	CONSTRAINT ENCARGO_IBFK_4
		FOREIGN KEY (ID_USUARIO) REFERENCES USUARIO (ID)
			ON UPDATE CASCADE ON DELETE CASCADE,
	CONSTRAINT ENCARGO_IBFK_5
		FOREIGN KEY (ID_TIPO_OPERACION) REFERENCES TIPO_OPERACION (ID)
			ON UPDATE CASCADE ON DELETE CASCADE
);

CREATE OR REPLACE INDEX ID_ESTADO
	ON ENCARGO (ID_ESTADO);

CREATE OR REPLACE INDEX ID_LIBRO
	ON ENCARGO (ID_LIBRO);

CREATE OR REPLACE INDEX ID_TIPO_ENTREGA
	ON ENCARGO (ID_TIPO_ENTREGA);

CREATE OR REPLACE INDEX ID_TIPO_OPERACION
	ON ENCARGO (ID_TIPO_OPERACION);

CREATE OR REPLACE INDEX ID_USUARIO
	ON ENCARGO (ID_USUARIO);

CREATE OR REPLACE TABLE TARJETA
(
	ID BIGINT(19) AUTO_INCREMENT
		PRIMARY KEY,
	NOMBRE_PERSONALIZADO VARCHAR(50) NULL,
	NUMERO BIGINT(16) NOT NULL,
	MES_CADUCIDAD INT NOT NULL,
	ANO_CADUCIDAD INT NOT NULL,
	CVV INT NOT NULL,
	ID_USUARIO BIGINT(19) NULL,
	ID_TIPO_TARJETA BIGINT(16) NULL,
	CONSTRAINT TARJETA_IBFK_1
		FOREIGN KEY (ID_USUARIO) REFERENCES USUARIO (ID)
			ON UPDATE CASCADE ON DELETE CASCADE,
	CONSTRAINT TARJETA_IBFK_2
		FOREIGN KEY (ID_TIPO_TARJETA) REFERENCES TIPO_TARJETA (ID)
			ON UPDATE CASCADE ON DELETE CASCADE
);

CREATE OR REPLACE TABLE COMPRA
(
	ID BIGINT(19) AUTO_INCREMENT
		PRIMARY KEY,
	FECHA_COMPRA DATE NOT NULL,
	FECHA_ENTREGA DATE NULL,
	METODO_PAGO FLOAT(6,2) NULL,
	ID_ESTADO BIGINT(19) NULL,
	ID_USUARIO BIGINT(19) NOT NULL,
	ID_TIPO_ENTREGA BIGINT(19) NOT NULL,
	ID_DIRECCION BIGINT(19) NULL,
	ID_TARJETA BIGINT(19) NULL,
	CONSTRAINT COMPRA_IBFK_1
		FOREIGN KEY (ID_ESTADO) REFERENCES ESTADO (ID)
			ON UPDATE CASCADE ON DELETE CASCADE,
	CONSTRAINT COMPRA_IBFK_2
		FOREIGN KEY (ID_USUARIO) REFERENCES USUARIO (ID)
			ON UPDATE CASCADE ON DELETE CASCADE,
	CONSTRAINT COMPRA_IBFK_3
		FOREIGN KEY (ID_TIPO_ENTREGA) REFERENCES TIPO_ENTREGA (ID)
			ON UPDATE CASCADE ON DELETE CASCADE,
	CONSTRAINT COMPRA_IBFK_4
		FOREIGN KEY (ID_DIRECCION) REFERENCES DIRECCION (ID)
			ON UPDATE CASCADE ON DELETE CASCADE,
	CONSTRAINT COMPRA_IBFK_5
		FOREIGN KEY (ID_TARJETA) REFERENCES TARJETA (ID)
			ON UPDATE CASCADE ON DELETE CASCADE
);

CREATE OR REPLACE INDEX ID_DIRECCION
	ON COMPRA (ID_DIRECCION);

CREATE OR REPLACE INDEX ID_ESTADO
	ON COMPRA (ID_ESTADO);

CREATE OR REPLACE INDEX ID_TARJETA
	ON COMPRA (ID_TARJETA);

CREATE OR REPLACE INDEX ID_TIPO_ENTREGA
	ON COMPRA (ID_TIPO_ENTREGA);

CREATE OR REPLACE INDEX ID_USUARIO
	ON COMPRA (ID_USUARIO);

CREATE OR REPLACE TABLE DETALLE_COMPRA
(
	ID_COMPRA BIGINT(19) NOT NULL,
	ID_LIBRO BIGINT(19) NOT NULL,
	CANTIDAD INT NOT NULL,
	PORCENTAJE_DESCUENTO DECIMAL(2) NULL,
	PRIMARY KEY (ID_COMPRA, ID_LIBRO),
	CONSTRAINT DETALLE_COMPRA_IBFK_2
		FOREIGN KEY (ID_COMPRA) REFERENCES COMPRA (ID)
			ON UPDATE CASCADE ON DELETE CASCADE,
	CONSTRAINT DETALLE_COMPRA_IBFK_3
		FOREIGN KEY (ID_LIBRO) REFERENCES LIBRO (ID)
			ON UPDATE CASCADE ON DELETE CASCADE
);

CREATE OR REPLACE INDEX ID_LIBRO
	ON DETALLE_COMPRA (ID_LIBRO);

CREATE OR REPLACE INDEX ID_TIPO_TARJETA
	ON TARJETA (ID_TIPO_TARJETA);

CREATE OR REPLACE INDEX ID_USUARIO
	ON TARJETA (ID_USUARIO);

CREATE OR REPLACE TABLE USUARIO_ROL
(
	ID_USUARIO BIGINT(19) NOT NULL,
	ID_ROL BIGINT(19) NOT NULL,
	PRIMARY KEY (ID_USUARIO, ID_ROL),
	CONSTRAINT USUARIO_ROL_IBFK_1
		FOREIGN KEY (ID_USUARIO) REFERENCES USUARIO (ID)
			ON UPDATE CASCADE ON DELETE CASCADE,
	CONSTRAINT USUARIO_ROL_IBFK_2
		FOREIGN KEY (ID_ROL) REFERENCES ROL (ID)
			ON UPDATE CASCADE ON DELETE CASCADE
);

CREATE OR REPLACE INDEX ID_ROL
	ON USUARIO_ROL (ID_ROL);

