INSERT INTO TIPO_ENTREGA (TIPO_ENTREGA)
VALUES ('RECOGIDA EN TIENDA') ,
    ('ENVIO A DOMICILIO');

INSERT INTO TIPO_OPERACION (TIPO_OPERACION)
VALUES ('CONSULTA') ,
    ('ENCARGO');

INSERT INTO APP_COMPONENTE (NOMBRE)
VALUES ('COMENTARIO'), ('COMPRA'), ('CONSULTA'), ('ENCARGO');

INSERT INTO ESTADO (ID_COMPONENTE, ESTADO)
VALUES
/*TABLA COMENTARIOS*/
    (1, 'PENDIENTE DE MODERAR') ,
    (1,'RECHAZADO')
    ,
    (1,'ACEPTADO')
    ,
/*TABLA COMPRA*/
    (2,'PENDIENTE DE PAGO')
    ,
    (2,'LISTO PARA RECOGIDA')
    ,
    (2,'PENDIENTE DE ENVIO')
    ,
    (2,'ENVIADO')
    ,
    (2,'PROCESADO')
    ,
/*TABLA CONSULTA*/
    (3,'ENVIADA')
    ,
    (3,'ABIERTA')
    ,
    (3,'FINALIZADA')
    ,
/*TABLA ENCARGO*/
    (4,'SOLICITADO')
    ,
    (4,'PENDIENTE DE PROCESAR')
    ,
    (4,'PENDIENTE RECOGIDA')
    ,
    (4,'FINALIZADO');
ALTER TABLE ESTADO
    ADD FOREIGN KEY (ID_COMPONENTE) REFERENCES APP_COMPONENTE (ID);

INSERT INTO ROL (NOMBRE_ROL)
VALUES ('ADMIN') ,
    ('CLIENTE');

insert into TIPO_TARJETA (NOMBRE)
VALUES ('VISA'), ('MASTERCARD');
