INSERT INTO TIPO_ENTREGA (TIPO_ENTREGA)
VALUES ('RECOGIDA EN TIENDA') ,
    ('ENVIO A DOMICILIO');

INSERT INTO TIPO_OPERACION (TIPO_OPERACION)
VALUES ('CONSULTA') ,
    ('ENCARGO');

INSERT INTO ESTADO (ESTADO)
VALUES
/*TABLA COMENTARIOS*/
    ('PENDIENTE DE MODERAR') ,
    ('RECHAZADO')
    ,
    ('ACEPTADO')
    ,
/*TABLA ENCARGO*/
/*TABLA COMPRA*/
    ('PENDIENTE DE PAGO')
    ,
    ('LISTO PARA RECOGIDA')
    ,
    ('PENDIENTE DE ENVIO')
    ,
    ('ENVIADO')
    ,
    ('PROCESADO')
    ,
/*TABLA CONSULTA*/
    ('ENVIADA')
    ,
    ('ABIERTA')
    ,
    ('FINALIZADA')
    ,
/*TABLA ENCARGO*/
    ('PENDIENTE RECOGIDA')
    ,
    ('PENDIENTE DE PROCESAR')
    ,
    ('FINALIZADO');

INSERT INTO ROL (NOMBRE_ROL)
VALUES ('ADMIN') ,
    ('CLIENTE')
    ,
    ('INVITADO');

$2a$10$SahsZm1o4Ig.fsyqNE/
fquGcp1MK7NtryVgxkEAvmYeer9N6KQ5M6
